### ISSUE TITLE
Publish this repository on website (uk.javascript.info)

### ISSUE THREAD

**Issue by p182** [javascript-tutorial/uk.javascript.info#139]
Зараз Javascript.info aka learn.javacript.ru доступний декількома мовами, але українська на сайті відсутня, хоча вже достатньо статей перекладено, будь ласка, опублікуйте статі на сайті, або додайте інструкцію, як сгенерувати статі для свого сайту

**Comment by tarasyyyk** [comment]
@p182 на даний момент українською не перекладено навіть четвертини всього матеріалу. Було б добре перекласти хоча б половину перед публікацією. На даний момент немає постійних перекладачів, які могли б перекладати хоча б 2 розділи в місяць. Але переклад триває, повільно але впевнено. А сам проєкт оновлюється майже кожного дня, тому вся інформація в ньому актуальна і буде дуже потрібна для майбутніх розробників. Завдяки небайдужим людям ми зможемо повністю перекласти посібник по javascript на українську мову!

**Comment by tarasyyyk** [comment]
@iliakan сколько минимально нужно перевести разделов, чтобы можно было опубликовать перевод (uk.javascript.info)?

**Comment by iliakan** [comment]
Хотя бы целиком первую часть. Обычно 50%+.

**Comment by stas-dolgachov** [comment]
@iliakan привет, если я правильно понимаю, уже переведено больше половины учебника. 

Подскажи, пожалуйста, что нужно сделать, чтобы перевод появился на сайте? 

Также работа над оставшимися статья ведется достаточно активно, нужно ли будет как-то настраивать деплой дополнительно чтобы они появлялись на сайте по мере перевода? 

@tarasyyyk

**Comment by stas-dolgachov** [comment]
Спасибо, сделаю завтра и отпишусь. @MykolaSopiha нужно будет, чтобы ты потом поревьювал, я с тобой спишусь отдельно ;)

**Comment by tarasyyyk** [comment]
Я ще не пішов у відпуск, а робота вже кипить. Супер!
Якщо буде потрібна моя допомога, гукайте.

**Comment by tarasyyyk** [comment]
@stas-dolgachov вдалося перекласти фрази з сайту?

**Comment by stas-dolgachov** [comment]
@tarasyyyk вибачаюсь за затримку, багато роботи було останнім часом. 
закінчу переклад сьогодні через кілька годин. Ще раз вибачаюсь

**Comment by stas-dolgachov** [comment]
@tarasyyyk @MykolaSopiha я закінчив перекладати фрази сайту. Для зручності я додав ці файли у Гіт в окремому репозиторії. Це зроблено для того, щоб ви могли порівняти із тим, що було. Після вашого ревью, я завантажу архів сюди. Додав вас у репозиторій, щоб ви могли робити зміни.

Ось мій комміт у якому весь переклад:
https://github.com/stas-dolgachov/uk-javascript-locale/commit/6785ba961bcaa0ec1ef789ea3a83c6d90ca128b3

Якщо ще когось потрібно буде додати, пишіть

**Comment by stas-dolgachov** [comment]
@iliakan привет, вот исправленная версия перевода фраз с сайта. 
Также я переименовал все ua.yml => uk.yml

[locales.zip](https://github.com/javascript-tutorial/uk.javascript.info/files/7904424/locales.zip)

**Comment by iliakan** [comment]
Выложил на прод.

**Comment by tarasyyyk** [comment]
> Выложил на прод.

Как быстро. Спасибо!

**Comment by iliakan** [comment]
Заголовок переведите, плиз:

![image](https://user-images.githubusercontent.com/349336/150348398-d6e7f7e5-dab5-4887-9807-810176559976.png)

**Comment by iliakan** [comment]
(деплой из учебника после коммита автоматический)

**Comment by stas-dolgachov** [comment]
Сейчас сделаю, спасибо @iliakan

**Comment by tarasyyyk** [comment]
Заголовки перекладено (завдяки @stas-dolgachov). Всі помилки на сайті і неточності в перекладі будемо записувати в [цьому обговорені](https://github.com/javascript-tutorial/uk.javascript.info/issues/267).
