### ISSUE TITLE
Словосполучення «default values»

### ISSUE THREAD

**Issue by tarasyyyk** [javascript-tutorial/uk.javascript.info#147]
Потрібно визначити, як будемо перекладати словосполучення **default values**. 
В [Словотворі](https://slovotvir.org.ua/words/bai-defolt) є декілька варіантів. Виберу найбільш популярні і виставлю на голосування. Особисто я за «типово».
Потрібно поставити реакцію під коментарем, щоб проголосувати. Можна вибрати декілька варіантів перекладу або додати свій.

Дата закінчення голосування **1 вересня 2021**.

**Comment by tarasyyyk** [comment]
(_значення_) **за замовчуванням**

**Comment by tarasyyyk** [comment]
**типові** (_значення_)

**Comment by tarasyyyk** [comment]
**усталені** (_значення_)

**Comment by tarasyyyk** [comment]
**задані** (_значення_)

**Comment by UkrainianCitizen** [comment]
https://ukrainian.stackexchange.com/a/5907/2097
https://ukrainian.stackexchange.com/questions/33/%d0%af%d0%ba-%d0%bf%d1%80%d0%b0%d0%b2%d0%b8%d0%bb%d1%8c%d0%bd%d0%be-%d0%bf%d0%b5%d1%80%d0%b5%d0%ba%d0%bb%d0%b0%d1%81%d1%82%d0%b8-default-value

**Comment by UkrainianCitizen** [comment]
За замовчуванням не валідним варіантом, бо це калька.

**Comment by UkrainianCitizen** [comment]
Для цього слова має бути набір валідних перекладів, якими можна перекладати залежно від контексту.

**Comment by tarasyyyk** [comment]
@UkrainianCitizen змінив голосування з `default` на `default values` і видалив варіант перекладу `значення за замовчуванням` тому що цей варіант перекладу однозначно не відповідний (враховуючи авторитетні джерела).

**Comment by tarasyyyk** [comment]
Голосування завершено. Вибрали варіант **типові значення**.
