### ISSUE TITLE
Translation: JavaScript Fundamentals > Operators

### ISSUE THREAD

**Issue by Zim123** [javascript-tutorial/uk.javascript.info#16]

**Comment by tarasyyyk** [comment]
@Zim123 How is going with translation?

**Comment by Zim123** [comment]
> @Zim123 How is going with translation?
Good so far.
I'm not sure if I should have created a pull request once I started translation to give you an ability to follow the progress?

Because, as you've seen, usually I make PR once I've ended the translation.

**Comment by tarasyyyk** [comment]
Translated in #19.
