### ISSUE TITLE
New maintainers

### ISSUE THREAD

**Issue by stas-dolgachov** [javascript-tutorial/uk.javascript.info#169]
Зважаючи на те, що переклад підручника прискорився, зросла і кількість активних пулл реквестів. 

Для того, щоб процесс перевірки пулл реквестів був кращий і швидший, я пропоную запропонувати активним перекладачам не тільки робити переклади, а також перевіряти переклади інших.

На мою думку, **"активний перекладач"** — це людина яка переклала дві або більше статей :) 

**Як я бачу цей процесс.** 
1. Новий maintainer перевіряє переклад та пропонує зміни до нього.
2. Після того, як ці зміни додано, новий maintainer додає своє схвалення на пулл реквест (approve).
3. @tarasyyyk перевіряє що все гаразд і приймає пулл реквест.

@tarasyyyk що думаєшь з цього приводу?

**Comment by tarasyyyk** [comment]
@stas-dolgachov це дуже хороша пропозиція.
Справді, відколи появилася більша кількість перекладачів, мені не вистачає часу на перевірку. Вже не кажучи на переклад. Адже я займаюся цим у вільний час, а щоб якісно перевірити і запропонувати зміни, потрібно ретельно і повністю прочитати розділ (бажано двічі).
Плюс, ніхто не скасовував людьський фактор – дві голови краще ніж одна, та й свіжий погляд ніколи не завадить.

**Comment by stas-dolgachov** [comment]
@tarasyyyk добре, у такому разі я запропоную перекладач долучитися до перевірки

**Comment by MykolaSopiha** [comment]
@tarasyyyk Привіт! Вибач, не звернув увагу, що грант на ментейнер права треба було апрувнути( Можеш, будь ласка, ще раз кинути, бо попередній реквест заекспайрився
![image](https://user-images.githubusercontent.com/20689588/147417299-6ebec65f-bd2c-42a6-a023-7860b18f966c.png)

**Comment by tarasyyyk** [comment]
@MykolaSopiha надіслав ще раз запит.

**Comment by astropsy999** [comment]
Доброго дня, чи можу я допомогти з перевіркою перекладів? Як це зробити? Мій pull request перекладу статті indexedDB  теж потребує перевірки, чи можливо прискорити? 🤔І ще питання, чи можу я взяти наступну статтю для перекладу, якщо попередня не перевірена? Дякую

**Comment by tarasyyyk** [comment]
@astropsy999, доброго дня. Призначив вашій обліковці деякі додаткові права до репозиторію. Підтвердіть запит (на пошті) і перевірте, чи можете коментувати інші запити на злиття (PR). Якщо можете коментувати, то ось як можна виправляти переклад:
![how-to-suggest-fixes](https://user-images.githubusercontent.com/20100011/171407764-596578ea-fd49-430c-b8b3-224cada013a2.png)
Проте краще буде, якщо ви візьмете і перечитаєте окрему статтю і виправите знайдені помилки через окремий PR.
[Ось тут ведеться облік](https://github.com/javascript-tutorial/uk.javascript.info/issues/281), які статті перевірені, та які ще потребують перевірки.

Ви можете брати наступну статтю, якщо попередню ще не перевірено. Я вже перевіряю ваш PR. Дякую за переклад, дуже якісний.

**Comment by tarasyyyk** [comment]
Надалі, якщо хтось захоче взяти участь в перевірці вже перекладений статтей, [пишіть в це обговорення](https://github.com/javascript-tutorial/uk.javascript.info/issues/281).
