### ISSUE TITLE
Відновлення прогрессу перекладу

### ISSUE THREAD

**Issue by stas-dolgachov** [javascript-tutorial/uk.javascript.info#170]
Нещодавно бот який відповідає за закріплення статей за перекладачами видалив з деяких статей відмітки, про те що вони вже готові. 

@tarasyyyk  Може ми якось можемо домогти? 

Наприклад, я можу зв'язатися з Ілльою Кантором і спитати як це віправити. Або можу якось це зробити у ручному режимі.

**Comment by tarasyyyk** [comment]
Доброго дня.
Я вже писав Іллі на рахунок цього, ще 27 липня. Але відповіді не отримав.
Коли буду мати час, тоді сам вручну все додам — в історії коментаря збережено весь прогрес.
Єдине питання в тому, чи не видалить знову бот мої зміни.

**Comment by tarasyyyk** [comment]
Прогрес відновив.
