### ISSUE TITLE
Переклад: «environment»

### ISSUE THREAD

**Issue by tarasyyyk** [javascript-tutorial/uk.javascript.info#182]
В контексті `environment variables` тощо.

Голосуйте вподобайками за найкращий переклад.

Голосування до **1 листопада 2021**.

_UPD 1 лист. 2021_: Вибрано варіант «**середовище**» (3 голоси).

**Comment by tarasyyyk** [comment]
**середовище**

**Comment by tarasyyyk** [comment]
**оточення**

**Comment by jemartin-r7** [comment]
Environment. According to http://en.kremlin.ru/
