### ISSUE TITLE
Переклад: «hard-coded»

### ISSUE THREAD

**Issue by tarasyyyk** [javascript-tutorial/uk.javascript.info#183]
Цим словом позначається код, змінна або значення, яке прописане в коді і не змінюється під час виконання скрипта.

Голосуйте вподобайками за найкращий варіант, або додавайте свої варіанти.

Голосування завершиться **1 листопада 2021**.

_UPD 1 лист. 2021_: варіанти «жорстко-кодоване» та «фіксоване» набрали одинакову кількість голосів — по 1 голосі. Я вирішив вжити більш зрозуміле слово «**фіксоване**». В перекладі можна додати в дужках англійський варіант. Наприклад: «_... оголосимо **фіксоване** (hard-coded) значення._»

**Comment by tarasyyyk** [comment]
**жорстко-кодоване**

**Comment by Regnised** [comment]
Фіксоване

**Comment by Regnised** [comment]
Статичне

**Comment by Regnised** [comment]
Константне
