### ISSUE TITLE
Баги на проде

### ISSUE THREAD

**Issue by dolgachio** [javascript-tutorial/uk.javascript.info#267]
Сегодня версия учебника стала доступна на украинском, с чем я всех нас поздравляю! 
В тоже время, т.к. перевод только только появился, возможно баги в его работе. 
Все находки предалгаю писать сюда, чтобы оперативно исправлять. 

По возможности пишите или на русском, т.к. с нами @iliakan , и насколько я знаю, он украинского не знает ;)

**Comment by stas-dolgachov** [comment]
1. В шапке сайта в меню выбора языка 
`Український` нужно изменить на `Українська`
2. Проблемы с открытием iframes  на страницах:
https://uk.javascript.info/testing-mocha
https://uk.javascript.info/event-delegation
https://uk.javascript.info/call-apply-decorators

**Comment by iliakan** [comment]
@stas-dolgachov 

Дякую.

Я стільки разів був в Україні, що український більш-менш розумію.

**Comment by Mouu9** [comment]
![image](https://user-images.githubusercontent.com/97622707/150576988-316e3c6b-be24-40e1-b061-fc04a737884d.png)
Пропоную замість кнопки "показати" зробити "відтворити", як написано нижче. Зараз не знаю, де це робиться

**Comment by tarasyyyk** [comment]
> Пропоную замість кнопки "показати" зробити "відтворити", як написано нижче. Зараз не знаю, де це робиться

@Mouu9 Переклад до самого сайту потрібно вносити в спеціальний файл, який не знаходиться в цьому репозиторії. В [цьому обговорені](https://github.com/javascript-tutorial/uk.javascript.info/issues/139#issuecomment-1015348936) @stas-dolgachov перекладав рядки для сайту. Потрібно вносити зміни в його файл і попросити Іллю залити зміни на сайт.
А переклад цієї кнопки краще змінити на «**виконати код**».

**Comment by iliakan** [comment]
вообще это HTML, вы уверены что именно виконати?

**Comment by iliakan** [comment]
как вариант ещё: показати результат

**Comment by Mouu9** [comment]
Дякую. Англійською там show, то мабуть "Відтворити" з тексту замінити?

**Comment by Nordtonito** [comment]
Помітив ось таке повідомлення в нещодавно перекладеній статті:
![Screenshot 2022-01-23 at 12 21 48](https://user-images.githubusercontent.com/43732023/150674139-08395765-8fbe-4d13-a7c3-4c25924cc3dc.png)

**Comment by tarasyyyk** [comment]
Привет, @iliakan !
Как узнать когда было последнее обновление перевода [для книги в](https://uk.javascript.info/ebook) `epub/pdf` формате?
[Есть проблема](https://github.com/javascript-tutorial/uk.javascript.info/issues/331) с тем, что не весь перевод на украинский доступен в оффлайн книге.

Я пробовал скачать демо фрагмент книги, то там пишет что «Построено 29 января 2022 р.»

**Comment by iliakan** [comment]
Посмотрю пересборку и отпишусь, спасибо.

**Comment by tarasyyyk** [comment]
> Посмотрю пересборку и отпишусь, спасибо.

@iliakan спасибо! Жду ответ
