### ISSUE TITLE
Translate:JavaScript Fundamentals::Hello, world!::Code structure

### ISSUE THREAD

**Issue by dDenysS** [javascript-tutorial/uk.javascript.info#3]
Translation for: 02-first-steps -> **01-hello-world**, **02-structure**

**Comment by dDenysS** [comment]
Why has "An introduction' is translated?

**Comment by tarasyyyk** [comment]
@dDenysS not only "Introductions" had been translated but also "Code editors" and "Devtools".
Thanks for your remark. I checked completed articles.

**Comment by tarasyyyk** [comment]
@dDenysS how is going with translation?

**Comment by dDenysS** [comment]
@tarasyyyk [commit](https://github.com/dDenysS/uk.javascript.info/commit/357f56bfef5d0a5f405edad65c24bf54b21b1788). I have little time. I think, I will translate small parts evere day next week

**Comment by tarasyyyk** [comment]
@dDenysS please, pull changes from master branch to sync last changes: https://github.com/javascript-tutorial/uk.javascript.info/pull/6/files#diff-80dd12d7fdb9adcfd831b2a4af1a33dd

**Comment by dDenysS** [comment]
@tarasyyyk I have just updated the code. [last changes](https://github.com/dDenysS/uk.javascript.info/commit/9f71bf9cd52cad508b2770dad1140ba45a0a21fb)

**Comment by tarasyyyk** [comment]
@dDenysS Are you going to also translate the section "JavaScript Fundamentals > **Code structure**" as well?

**Comment by tarasyyyk** [comment]
@dDenysS how is going with translation?

**Comment by tarasyyyk** [comment]
Translated "**Code structure**" in PR #25.

**Comment by tarasyyyk** [comment]
Translated "**Hello, world**" in commit https://github.com/javascript-tutorial/uk.javascript.info/commit/a79419ea7d64f5c4ab3e26226ebc5bdb466b16c2.
Translation text moved from source commits in forked repository: https://github.com/javascript-tutorial/uk.javascript.info/commit/357f56bfef5d0a5f405edad65c24bf54b21b1788 and https://github.com/javascript-tutorial/uk.javascript.info/commit/9f71bf9cd52cad508b2770dad1140ba45a0a21fb, updated and merged to `master` branch.

**Comment by dDenysS** [comment]
@tarasyyyk Thank you for your message.  I will continue to translate tomorrow

**Comment by tarasyyyk** [comment]
No need, @dDenysS . These chapters already translated. Thank you for your work!

**Comment by tarasyyyk** [comment]
Thank you for contribution!
@all-contributors add @dDenysS for translation.
