### ISSUE TITLE
Проблема з мовою

### ISSUE THREAD

**Issue by Aloscha95** [javascript-tutorial/uk.javascript.info#331]
Придбав книгу, проте третя книга не на українській мові, хоча декілька відсотків тексту на українській. Як би виправити цей нюанс?

**Comment by tarasyyyk** [comment]
Доброго дня. Я уточню це питання.
Дякую що описали проблему!

**Comment by Aloscha95** [comment]
Доброго вечора, буду вдячний, ще в книгах не відсилає на посилання щодо відповідей на завдання. Буду вдячний за вирішення цих нюансів. Дякую!

26 квітня 2022, 23:07:22, від "Taras" < ***@***.*** >:



Доброго дня. Я уточню це питання.
Дякую що описали проблему!

**Comment by iliakan** [comment]
перевірте зараз, будь ласка?

**Comment by tarasyyyk** [comment]
Я спробував згенерувати демо-зразок, то в ньому пише, що згенеровано «29 січня 2022 р» (як в pdf, так і в epub форматах).

Можливо ще @Aloscha95 перевірить повну версію підручника.

**Comment by Aloscha95** [comment]
В демо- версії все чітко, а от в скачаному підручнику -ні. І гіперсилки не працюють, які стосуються відповідей на завдання.

8 травня 2022, 10:28:41, від "Taras" < ***@***.*** >:



Я спробував згенерувати демо-зразок, то в ньому пише, що згенеровано «29 січня 2022 р» (як в pdf, так і в epub форматах).

Можливо ще @Aloscha95 перевірить повну версію підручника.

**Comment by Aloscha95** [comment]
Все залишилось по-старому.

8 травня 2022, 04:14:28, від "Ilya Kantor" < ***@***.*** >:



перевірте зараз, будь ласка?

**Comment by iliakan** [comment]
Була помилка у перекладі, через яку авто-деплою не проходив. Начебто поправив. А зараз?

**Comment by tarasyyyk** [comment]
@Aloscha95 можете перевірити, чи поправився переклад?

**Comment by Aloscha95** [comment]
так, з перекладом все добре. ссилки не працюють на відповіді щодо завдань.

16 травня 2022, 21:19:41, від "Taras" ***@***.***>:


@Aloscha95 можете перевірити, чи поправився переклад?

**Comment by tarasyyyk** [comment]
@Aloscha95:
> так, з перекладом все добре. ссилки не працюють на відповіді щодо завдань. 16 травня 2022, 21:19:41, від "Taras" ***@***.***>: @Aloscha95 можете перевірити, чи поправився переклад? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

Чи могли б перевірити посилання на відповіді чи вони працюють?
