### ISSUE TITLE
Слово "statement"

### ISSUE THREAD

**Issue by tarasyyyk** [javascript-tutorial/uk.javascript.info#36]
Вибираємо кращий переклад слова `statement`. В контексті "частина JavaScript коду, який буде виконуватися на сторінці".
Наприклад:
```
Statements are delimited with a semicolon:
alert('Hello'); alert('World');
```
Варіанти:

- **конструкція**. Використовується в [MDN](https://developer.mozilla.org/uk/docs/Learn/Getting_started_with_the_web/JavaScript_basics#Умови). Мені подобається цей варіант.
- **інструкція**. Поточний переклад. Використовується в [російській версії](https://github.com/javascript-tutorial/ru.javascript.info/blob/master/1-js/02-first-steps/02-structure/article.md#инструкции) цього посібника.
- ~~**вираз**~~ _Не підходить для даного слова. "`Вираз`" буде використовуватися для `expression`_.
- **команда**. Використовується на сайті [javascript.ru](https://learn.javascript.ru/structure).

Опитування:

[![](https://api.gh-polls.com/poll/01DGCZC8DMP7A53BRC783S573M/%D0%BA%D0%BE%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%86%D1%96%D1%8F)](https://api.gh-polls.com/poll/01DGCZC8DMP7A53BRC783S573M/%D0%BA%D0%BE%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%86%D1%96%D1%8F/vote)
[![](https://api.gh-polls.com/poll/01DGCZC8DMP7A53BRC783S573M/%D1%96%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%86%D1%96%D1%8F)](https://api.gh-polls.com/poll/01DGCZC8DMP7A53BRC783S573M/%D1%96%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%86%D1%96%D1%8F/vote)
[![](https://api.gh-polls.com/poll/01DGCZC8DMP7A53BRC783S573M/%D0%B2%D0%B8%D1%80%D0%B0%D0%B7)](https://api.gh-polls.com/poll/01DGCZC8DMP7A53BRC783S573M/%D0%B2%D0%B8%D1%80%D0%B0%D0%B7/vote)
[![](https://api.gh-polls.com/poll/01DGCZC8DMP7A53BRC783S573M/%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%B0)](https://api.gh-polls.com/poll/01DGCZC8DMP7A53BRC783S573M/%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%B0/vote)

**Comment by tarasyyyk** [comment]
Опитування триває до 1 жовтня 2019 року.
Нові варіанти перекладу пропонуйте в цьому issue.

**Comment by Zim123** [comment]
Взагалі, на мою думку, і "вираз" і "конструкція" гарні варіанти, в одному випадку один добре пасує, в іншому — другий. У прикладі вище, як на мене, то "вираз" краще підходить, але "конструкція" також валідний варіант. Чи не можно використовувати обидва варіанти, в залежності від контексту?

**Comment by tarasyyyk** [comment]
@Zim123 подивимося, яким буде результат опитування. Якщо ці два варіанти наберуть більш-менш одинакові кількості голосів, то виберемо обидва варіанти.

**Comment by UkrainianCitizen** [comment]
Із оксфордського словника:
> A statement is something that you say or write which gives information in a formal or definite way. 

Серед наданих варіантів, лише `вираз` найкраще підходить під подібне визначення слова.

**Comment by UkrainianCitizen** [comment]
Але такий переклад `вираз` конфліктує із словом `expression`, адже там також треба перекладати `вираз`. Тут при перекладі потрібно врахувати все.

**Comment by tarasyyyk** [comment]
@UkrainianCitizen в такому випадку переклад `вираз` відпадає для слова `statement`. Можу що, `expression` доволі часто буде зустрічатися в наступних розділах.

**Comment by Zim123** [comment]
@UkrainianCitizen @tarasyyyk 
А чом би і ні? Є таке поняття як синонім, якщо в одному реченні вони будуть зустрічатися, то statement можно перекласти як "конструкція", якщо ні — то можно як "вираз". Я взагалі не бачу проблеми. Тим паче, що у "інструкції по перекладу" було сказано, що не обов'язково дослівно переводити, можно близько за змістом.

**Comment by UkrainianCitizen** [comment]
@Zim123 В українській мові, це синоніми, але в англійській - це два різних слова, які в контексті програмування вживаються в різних випадках, тому і для перекладу треба вживати два різних слова.
Вікі - ненадійне джерело, але там `expression` перекладають як `вираз`. Також виходячи із тлумачення і use cases англ. відповідника, це, зрештою, `вираз`.

@Zim123 @tarasyyyk [Англійська вікі](https://en.wikipedia.org/wiki/Statement_(computer_science)) пише, що `statement` - це синтаксичний юніт, який виражає якусь дію, яка має бути виконана.
Виходячи з такого визначення, це може бути або `команда`(на якусь дію/дії) або `інструкція`(щось зробити). `Конструкція` відпадає.

[Українська вікі](https://uk.wikipedia.org/wiki/%D0%86%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%86%D1%96%D1%8F_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F)) перекладає як `інструкція`. І хоча, це, можливо, не на 100% правда, пропоную прийняти це слово.
 Крім того, вживання `команда` як перекладу мені здається некоректним у випадку деяких `statement` таких як відкриття блоку conditional logic, адже, по суті, це не команда, а радше дійсно інструкція на певні дії. В цьому випадку, переклад ` інструкція` є менш некоректною, ніж `команда`, якщо розглядати use cases в загальному.

**Comment by tarasyyyk** [comment]
@UkrainianCitizen тоді слово `expression` краще перекладати як `вираз`?
Зараз для `statement` якраз і використовується слово `інструкція`. В такому випадку нічого міняти не прийдеться.

**Comment by UkrainianCitizen** [comment]
@tarasyyyk Я думаю, що так.

**Comment by lobanov-oleh** [comment]
У випадку з `The "switch" statement` **конструкція** максимально влучний із перерахованих варіант. Тому я за **statement** = **конструкція** :-)

**Comment by UkrainianCitizen** [comment]
> У випадку з `The "switch" statement` **конструкція** максимально влучний із перерахованих варіант. Тому я за **statement** = **конструкція** :-)

Це лише часткова правда у випадку із switch. Не хочу повторюватися чому це неправильно, почитайте [мою відповідь]([url](https://github.com/javascript-tutorial/uk.javascript.info/issues/36#issuecomment-517147930)). Крім того, є слово `construct` переклад, якого 100% конструкція, що конфліктує з таким варіантом перекладу.

**Comment by hypeofpipe** [comment]
Вікіпедія говорить наступне:
"Констру́кція (constructio, від con — «разом», «з» та struere — «будувати»)"

Особисто я собі уявив особу недосвідчену в програмуванні, і мені здається, що це може бути за важко і не зрозуміло для неї. Особисто мене такі незрозумілі слова завжди відлякували на початку вивчення певної мови програмування. З точки зору читабельності, моєю думкою, підійде слово "**інструкція**" – де-факто, певна лінія коду є інструкцією для транспілятора або компілятора

**Comment by tarasyyyk** [comment]
Опитування завершено. Згідно результатів, для слова `statement` буде використовуватися український відповідник «**інструкція**». Слово додано до [Глосарію](https://github.com/javascript-tutorial/uk.javascript.info/issues/8#issue-441204008).
Знімок опитування:
![Слово  statement  · Issue #36 · javascript-tutorial:uk javascript info 2019-10-01 10-40-39](https://user-images.githubusercontent.com/20100011/65943448-2285b400-e438-11e9-8472-5d59df84936a.jpg)

**Comment by UkrainianCitizen** [comment]
Не побачив *operator* i *operand* в словнику.

**Comment by tarasyyyk** [comment]
@UkrainianCitizen так і перекладатимемо: _operator_ => **оператор** i _operand_ => **операнд**.

**Comment by UkrainianCitizen** [comment]
@tarasyyyk не в той тред написав, але вже закінчу тут. Це треба в глосарій додати.
