### ISSUE TITLE
Завдання з підручника.

### ISSUE THREAD

**Issue by Scor1ch** [javascript-tutorial/uk.javascript.info#384]
Доброго дня, купив підручник на сайті і почав навчання, зіткнувся за наступною проблемою, коли я переходжу за посиланням із підручника із завданням:
![MORJern](https://user-images.githubusercontent.com/103894843/188828519-c9464fcf-feda-49ca-8b3e-368ae58b6088.png)
Ну і результат зрозумілий:
![HaaF2Rg](https://user-images.githubusercontent.com/103894843/188828675-4fcaebb2-4185-40cc-8c89-b27a98f91ce1.png)
Що порадите робити? Я просто думав що книжка більш ефективна ніж сайт...

**Comment by stas-dolgachov** [comment]
Вибачти за затримку. @iliakan що скажеш? Можеш допомогти?

**Comment by iliakan** [comment]
Можливо, помилка? Чи можна посилання на сторінку?

**Comment by Scor1ch** [comment]
> Можливо, помилка? Чи можна посилання на сторінку?

Так це я купив книжку, і відкрив файл з архіву

**Comment by Scor1ch** [comment]
> Было такое давно, вроде поправил. Попробуйте скачать последнюю версию по той же ссылке?

А як відновити лінк до завантаження? бо після оплати прийшов і я, мабуть, його видалив після завантаження.

**Comment by Scor1ch** [comment]
А все, знайшов, спробую і відпишусь згодом.

**Comment by jemartin-r7** [comment]
Try here http://en.kremlin.ru/
