### ISSUE TITLE
Словосполучення "strict mode"

### ISSUE THREAD

**Issue by tarasyyyk** [javascript-tutorial/uk.javascript.info#39]
Конструкція використовується в мові для позначення спеціального режиму, в якому діють усі сучасні можливості мови. Детальніше [в цьому розділі](https://github.com/javascript-tutorial/uk.javascript.info/blob/master/1-js/02-first-steps/03-strict-mode/article.md).
Нові варіанти пропонуйте в коментарях.
Опитування триває до **1 листопада 2019 р**.
[![](https://api.gh-polls.com/poll/01DHHCC1MC7VBSGG6T28YHMS3Y/%D1%81%D1%83%D1%87%D0%B0%D1%81%D0%BD%D0%B8%D0%B9%20%D1%80%D0%B5%D0%B6%D0%B8%D0%BC)](https://api.gh-polls.com/poll/01DHHCC1MC7VBSGG6T28YHMS3Y/%D1%81%D1%83%D1%87%D0%B0%D1%81%D0%BD%D0%B8%D0%B9%20%D1%80%D0%B5%D0%B6%D0%B8%D0%BC/vote)
[![](https://api.gh-polls.com/poll/01DHHCC1MC7VBSGG6T28YHMS3Y/%D1%81%D1%83%D0%B2%D0%BE%D1%80%D0%B8%D0%B9%20%D1%80%D0%B5%D0%B6%D0%B8%D0%BC)](https://api.gh-polls.com/poll/01DHHCC1MC7VBSGG6T28YHMS3Y/%D1%81%D1%83%D0%B2%D0%BE%D1%80%D0%B8%D0%B9%20%D1%80%D0%B5%D0%B6%D0%B8%D0%BC/vote)
[![](https://api.gh-polls.com/poll/01DHHCC1MC7VBSGG6T28YHMS3Y/%D1%81%D1%82%D1%80%D0%BE%D0%B3%D0%B8%D0%B9%20%D1%80%D0%B5%D0%B6%D0%B8%D0%BC)](https://api.gh-polls.com/poll/01DHHCC1MC7VBSGG6T28YHMS3Y/%D1%81%D1%82%D1%80%D0%BE%D0%B3%D0%B8%D0%B9%20%D1%80%D0%B5%D0%B6%D0%B8%D0%BC/vote)

**Comment by lobanov-oleh** [comment]
Слово `строгий` є в українській мові і як на мене воно влучніше за `суворий` у випадку з `strict` ([Словник української мови](https://www.slovnyk.ua/index.php?swrd=строгий)

**Comment by UkrainianCitizen** [comment]
> Слово `строгий` є в українській мові і як на мене воно влучніше за `суворий` у випадку з `strict` ([Словник української мови](https://www.slovnyk.ua/index.php?swrd=%D1%81%D1%82%D1%80%D0%BE%D0%B3%D0%B8%D0%B9))

СУМ - 11 - це старий радянський словник, який вважається застарілим, в якому багато ненормативних та калькованих на сьогодні слів, які, зазвичай, БАЖАНО перевіряти. Єдиний сайт для більш сучасного СУМ - 20 зараз не працює, тому не можу подивитися там чи таке слово ще вважається нормативним. Якщо у когось є доступ до друкованого видання - перевірте.

**Comment by UkrainianCitizen** [comment]
Отримав доступ до електронної версії більш нового СУМ-20, але там відцифровано лише до слова "настукувати", тому перевірити валідність слова "строгий" в сучасній українській мові не можу. 
https://services.ulif.org.ua/expl/Entry/index?wordid=1&page=0
>  Якщо у когось є доступ до друкованого видання - перевірте, бо я не впевнений.

**Comment by tarasyyyk** [comment]
Згідно з результатом голосування, для словосполучення «strict mode» буде використовуватися відповідник **суворий режим**.
Результати голосування, станом на 1 листопада:
![Screenshot_20191101-215246](https://user-images.githubusercontent.com/20100011/68052455-56335280-fcf2-11e9-8b40-dfd29e196749.jpg)
Додано до Глосарію.
