### ISSUE TITLE
"Створіть обговорення" з малої літери

### ISSUE THREAD

**Issue by yokoole** [javascript-tutorial/uk.javascript.info#414]
![image](https://user-images.githubusercontent.com/116198926/199981964-ed0b620b-413f-4030-bc9e-b3e09197738a.png)

**Comment by tarasyyyk** [comment]
Поправили текст в README:
------------------------------
![image](https://github.com/javascript-tutorial/uk.javascript.info/assets/20100011/f14de0a3-7376-409c-b423-39135c78e76e)

Дякуємо!

**Comment by tarasyyyk** [comment]
@all-contributors please add @yokoole for bug.
