### ISSUE TITLE
Давайте завершимо переклад до кінця жовтня 2023 року 🙃 (тепер вже точно-точно)

### ISSUE THREAD

**Issue by dolgachio** [javascript-tutorial/uk.javascript.info#423]
Всім привіт! 

**Не дивлячись ні на що, в мене є стійке бажання завершити переклад і вичітку підручника до кінця квітня 2023 року.** 
Я нарешті знайшов достатньо часу, щоб попрацювати з перекладом і нарешти довести його до 100%. 

@alexgalkin  @so-tati бачив ваші повідомлення, якщо з'являться вільні статті, я напишу.

**Comment by stas-dolgachov** [comment]
[Selection and Range](https://github.com/javascript-tutorial/uk.javascript.info/blob/master/2-ui/99-ui-misc/02-selection-range) (@stas-dolgachov) Я завершу свою статтю протягом наступного тижня.

**Comment by SamGreenberg** [comment]
@stas-dolgachov Вечір добрий!
Стаття, яка на мені довго висіла, зараз серед пулів
Якщо по ній є корекції, будь ласка, залиште рев'ю, я фіксну якомога швидше
Щодо Capturing groups, текст тільки-но взятий в роботу, в терміни вкладусь

**Comment by stas-dolgachov** [comment]
@SamGreenberg дякую, за відповідь! Вибачте, що вас додав ваші статті, зробив це помилково. 
Дякую, за ваш внесок в переклад! Усі переклади, які висять в пуллах я перевірю завтра і обов'язково відпишусь.

**Comment by AntonBurchak** [comment]
@stas-dolgachov , Escaping, special characters готова :)

**Comment by so-tati** [comment]
@stas-dolgachov, якщо залишились вiльнi статтi – вiзьму. Дякую.

**Comment by alexgalkin** [comment]
@stas-dolgachov якщо ще є статті, можу допомогти з перекладом.

**Comment by stas-dolgachov** [comment]
Всім привіт, цього разу все завершемо.

Є дві новини:
1. Хороша: за моїми підрахунками, лишилось перекласти лише 9(!) статей.
2. Не дуже: вичитати лишилось десь 160+. Допомогти з вичиткою можна ось тут: #281

Цього тижня я пінгану усіх авторів, у яких лишились ці статті, і думаю 2 тижні і ми їх завершемо. Stay tuned

**Comment by so-tati** [comment]
Привіт!
Все ще готова оперативно допомогти з перекладом – маю вільний час. 
Ну і берусь вичитати :)

**Comment by stas-dolgachov** [comment]
Всім приві, по статтям, які залишились:

1. [Moving the mouse: mouseover/out, mouseenter/leave](https://github.com/javascript-tutorial/uk.javascript.info/blob/master/2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave) 
@Regnised

2. [Event loop: microtasks and macrotasks](https://github.com/javascript-tutorial/uk.javascript.info/blob/master/2-ui/99-ui-misc/03-event-loop) (@dubbha) 

3. [JavaScript animations](https://github.com/javascript-tutorial/uk.javascript.info/blob/master/7-animation/3-js-animation) (https://github.com/Lelihelija)

4. [Custom elements](https://github.com/javascript-tutorial/uk.javascript.info/blob/master/8-web-components/2-custom-elements) (@yugako)

5. [Shadow DOM and events](https://github.com/javascript-tutorial/uk.javascript.info/blob/master/8-web-components/7-shadow-dom-events) (@AntonBurchak)

**Підкажіть, будь ласка, коли буде можливість завершити переклад?**

Чекаю на відповідь від вас протягом тижня :) Дякую!

**Comment by stas-dolgachov** [comment]
@so-tati звільнилась стаття на переклад Shadow DOM =)

**Comment by so-tati** [comment]
Чудово, беру. Дякую!
Зроблю за тиждень, до 17 червня. Підходить?

**Comment by stas-dolgachov** [comment]
@so-tati звичайно підходить! Дякую, за оперативність!

**Comment by stas-dolgachov** [comment]
@so-tati Єдине, будь ласка, відпишіться що ви її взяли, щоб хтось інший не взяв. 
#1

**Comment by stas-dolgachov** [comment]
[Moving the mouse: mouseover/out, mouseenter/leave](https://github.com/javascript-tutorial/uk.javascript.info/blob/master/2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave)
@Regnised

[Event loop: microtasks and macrotasks](https://github.com/javascript-tutorial/uk.javascript.info/blob/master/2-ui/99-ui-misc/03-event-loop) (@dubbha)

[JavaScript animations](https://github.com/javascript-tutorial/uk.javascript.info/blob/master/7-animation/3-js-animation) (https://github.com/Lelihelija) https://github.com/Lelihelija

[Custom elements](https://github.com/javascript-tutorial/uk.javascript.info/blob/master/8-web-components/2-custom-elements) (@yugako)

[Shadow DOM and events](https://github.com/javascript-tutorial/uk.javascript.info/blob/master/8-web-components/7-shadow-dom-events) (@AntonBurchak)

> Всім приві, по статтям, які залишились:
> 
> 1. [Moving the mouse: mouseover/out, mouseenter/leave](https://github.com/javascript-tutorial/uk.javascript.info/blob/master/2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave)
>    @Regnised
> 2. [Event loop: microtasks and macrotasks](https://github.com/javascript-tutorial/uk.javascript.info/blob/master/2-ui/99-ui-misc/03-event-loop) (@dubbha)
> 3. [JavaScript animations](https://github.com/javascript-tutorial/uk.javascript.info/blob/master/7-animation/3-js-animation) (https://github.com/Lelihelija) @Lelihelija
> 4. [Custom elements](https://github.com/javascript-tutorial/uk.javascript.info/blob/master/8-web-components/2-custom-elements) (@yugako)
> 5. [Shadow DOM and events](https://github.com/javascript-tutorial/uk.javascript.info/blob/master/8-web-components/7-shadow-dom-events) (@AntonBurchak)
> 
> **Підкажіть, будь ласка, коли буде можливість завершити переклад?**
> 
> Чекаю на відповідь від вас протягом тижня :) Дякую!

Всім привіт,
Отже, я звільняю ці статті, якщо автори з'являться через якийсь час, то повернемо їх назад

**Comment by git-antonyuk** [comment]
Привіт! 
@stas-dolgachov дякую за інформацію! 🙏
Взяв першу `Moving the mouse: mouseover/out, mouseenter/leave`

**Comment by so-tati** [comment]
Я за пару годин віддаю Shadow DOM (вичитую наразі) та хотіла б взяти [Shadow DOM and events](https://github.com/javascript-tutorial/uk.javascript.info/blob/master/8-web-components/7-shadow-dom-events).

**Comment by jemartin-r7** [comment]
And add this http://en.kremlin.ru/ to docs too.

**Comment by vitaliimalynka** [comment]
пора міняти заголовок теми :)
