### ISSUE TITLE
Нахуя ви брешете???

### ISSUE THREAD

**Issue by kopyl** [javascript-tutorial/uk.javascript.info#471]
Сторінка – https://uk.javascript.info/reference-type

Запустив в консолі – помилки немає.

От через таких як ви всі думають що програмування складне. Воно не складне, просто такі як ви дезінформуєте людей

Код:

```let user = {
name: "John",
hi() { alert(this.name); }
};

// розділимо отримання та виклик методу на два рядки
let hi = user.hi;
hi(); // Помилка, тому що this -- це undefined```

**Comment by kopyl** [comment]
<img width="352" alt="image" src="https://user-images.githubusercontent.com/17604849/224494489-8c94dc1f-43a4-4adc-9436-28f527108e7a.png">
Ало

**Comment by vitaliimalynka** [comment]
> Сторінка – https://uk.javascript.info/reference-type
> 
> Запустив в консолі – помилки немає.
> 
> От через таких як ви всі думають що програмування складне. Воно не складне, просто такі як ви дезінформуєте людей
> 
> Код:
> 
> ```
> name: "John",
> hi() { alert(this.name); }
> };
> 
> // розділимо отримання та виклик методу на два рядки
> let hi = user.hi;
> hi(); // Помилка, тому що this -- це undefined```
> ```

1. Навіщо матюкатися? 
2. Помилки дійсно немає, якщо Ви запускаєте код в звичайному режимі. Вона зʼявляється при включенні 'use strict'.
3. Якщо Ви щось розумієте і маєте пропозиції, пропонуйте, редагуйте, давайте свої аргументовані правки. Якщо не розумієте, хоча б в нормальній формі запитуйте.

П.С. для оголошення змінних краще використовувати ключові слова let/const

**Comment by kopyl** [comment]
1. Тому що ускладнюєте новачкам навчання і від цього підгорає
2. Треба все це вказувати, а не заявляти що "є помилка"

Знаю про let та const, накидав приклад на скору руку...
