### ISSUE TITLE
У вибраній мною статті відсутні файли для перекладу

### ISSUE THREAD

**Issue by vitaliimalynka** [javascript-tutorial/uk.javascript.info#507]
Вітаю.
Перейшов до перекладу наступної вільної статті [Unicode, String internals](https://github.com/javascript-tutorial/uk.javascript.info/blob/master/1-js/99-js-misc/06-unicode)

Як виявилося, файли для перекладу за вказаним посиланням відсутні.

Я можу самостійно їх витягнути з англомовної версії, чи перед її перекладом хтось із супроводжувачів повинен синхронізувати ці репозиторії?

**Comment by stas-dolgachov** [comment]
@vitaliimalynka добрий день, дякую, що звернули на це увагу. Скоріш за все, я маю синхронізувати наш переклад з оригінальною версією вручну. 

Раніше це відбувалось автоматично. Я зараз спробую і напишу вам.

**Comment by stas-dolgachov** [comment]
@vitaliimalynka зробив спробу синхронізації, там роботи на 2-3 години, щоб все вичитати і перевірити, може навіть більше. 

Думаю, закінчу сьогодні ввечері або завтра вранці. Тому орієнтуйтесь, будь ласка, що ваша стаття з'явиться завтра. Проте, ви вже можете розпочати переклад, взявши текст статті з оригіналу - https://github.com/javascript-tutorial/en.javascript.info/tree/master/1-js/99-js-misc/06-unicode

**Comment by vitaliimalynka** [comment]
Вітаю, @stas-dolgachov.
Дякую за швидку відповідь. В принципі я вже пішов по альтернативному шляху, щонайменше, вже будуть напрацювання, а далі розберемось.

**Comment by vitaliimalynka** [comment]
Можливо, із синхронізацією зʼявляться ще статті, бо вже доступних для преекладу не лишилось, бачу тільки ті, які довго висять на комусь і поки не рухаються

**Comment by stas-dolgachov** [comment]
Станом на зараз так і є, проте можна допомогти з вичиткою, бо це також дуже важливо. Подробиці ось тут: #281

**Comment by vitaliimalynka** [comment]
Стасе, я вже готовий залити переклад. 
Вже можу, чи ще почекати?

**Comment by stas-dolgachov** [comment]
@vitaliimalynka почекайте, будь ласка, я не встиг вчора закинути. Сьогодні ввечері закінчу. Вибачаюсь за затримку, там трошки більше ніж я думав :)

**Comment by vitaliimalynka** [comment]
я помітив, що щось не так. 
Очікую від Вас відмашку

**Comment by stas-dolgachov** [comment]
@vitaliimalynka дуже вибачаюсь за затримку, там величезний шмат роботи і рухається все досить повільно. Пропоную вам альтернативний варіант. Додайте, будь ласка, цей файл до нашої версії посібника тут, а я вже пофікшу конфлікти як закінчу. Єдине бажано щоб структура файлів і назва файлу були такі самі як і в оригіналі.

**Comment by vitaliimalynka** [comment]
Вітаю.
Зробив запит на злиття. 
Структуру взяв з англійської версії. Якщо не протупив, то все повинно сходитися :)
