### ISSUE TITLE
Розділ 3.5. Помилка у слові "всередині", написано "всереді".

### ISSUE THREAD

**Issue by YevhenOstrovskiy** [javascript-tutorial/uk.javascript.info#551]
![Screenshot 2023-09-13 103303](https://github.com/javascript-tutorial/uk.javascript.info/assets/92674052/50450ff7-481e-46bc-b2fe-1a03460e68c7)

**Comment by taleksina** [comment]
Виправлено, додано до Pull request #550

**Comment by tarasyyyk** [comment]
@all-contributors add @YevhenOstrovskiy for bug find

**Comment by tarasyyyk** [comment]
@taleksina @YevhenOstrovskiy, дякуємо за ваші внески!
