### ISSUE TITLE
Завантаження книги

### ISSUE THREAD

**Issue by Scor1ch** [javascript-tutorial/uk.javascript.info#563]
Вітаю, купував давно книгу, знайшов лист на пошті і вирішив оновити у пам'яті інформацію, а лінк вже 404, як бути?

**Comment by dolgachio** [comment]
@iliakan привіт, допоможи, будь ласка

**Comment by dolgachio** [comment]
@iliakan ping ping

**Comment by dolgachio** [comment]
@Scor1ch напишіть будь ласка Іллі Кантору на пошту, бо тут він чомусь не бачить повідомлень, на жаль
