### ISSUE TITLE
a small mistake

### ISSUE THREAD

**Issue by fabrikatoroleg** [javascript-tutorial/uk.javascript.info#592]
Привіт. Це звісно не велика, але ж помилка. 
https://uk.javascript.info/regexp-introduction
Глава Регулярні вирази
Заміна: str.replace
У прикладі 
// без прапора g
alert( "Ми будемо, ми будемо".replace(/ми/i, "Я") ); // Я будемо, я будемо 
треба замінити на 
alert( "Ми будемо, ми будемо".replace(/ми/i, "Я") ); // Я будемо, ми будемо

**Comment by tarasyyyk** [comment]
Fixed in [this commit](https://github.com/javascript-tutorial/uk.javascript.info/commit/1cfad66f4c39e85fe7b95d839b25e224b298fee5). Thanks for notice

**Comment by tarasyyyk** [comment]
<img width="636" alt="a small mistake · Issue #592 · javascript-tutorial:uk javascript info 2024-02-24 22-19-08" src="https://github.com/javascript-tutorial/uk.javascript.info/assets/20100011/7ea13ebc-63b7-420c-b422-51f84992f22b">
